### ISSUE TITLE
Confusing statement on project/external-modules.md

### ISSUE THREAD

**Issue by thefabulousdev** [basarat/typescript-book#100]
[As seen here](https://github.com/basarat/typescript-book/blob/master/docs/project/external-modules.md#import-type-only)

> ### Import type only
The following statement:
```ts
import foo = require('foo');
```
actually imports *two* things:
* The type information from the imported file.
* Takes are runtime dependency on the `foo` module.

> You can pick and choose so that only *the type information* is loaded and no runtime dependency occurs. Before continuing you might want to recap the [*declaration spaces*](../project/declarationspaces.md) section of the book.

What does the second list item meant? Perhaps it should be

> * The runtime dependencies on the `foo` module

If it is what was meant with the statement, I'll submit a PR .

**Comment by basarat** [comment]
> Takes are runtime dependency on the foo module.

i.e. the current file cannot work unless `foo` is loaded first

**Comment by thefabulousdev** [comment]
I believe the statement doesn't make sense grammatically, I have consulted with a few colleagues which are native english speakers and also find it confusing. 

The sentence should be read as an extension of `actually imports two things:`, meaning read as 

> actually imports two things: Takes are runtime dependency on the foo module.

I believe it should still be rephrased.

**Comment by basarat** [comment]
> I believe it should still be rephrased.

Agreed :rose: How about: 

> Actually does two things:

> * Imports the type information of the foo module.
* Specifes a runtime dependency on the foo module.

**Comment by thefabulousdev** [comment]
Way better! Make the `Specifes` a `Specifies` and good to go 😄 , should I change it or do you have time?

**Comment by basarat** [comment]
I'll do it an reference :rose:
