### ISSUE TITLE
Expand section on Contributing

### ISSUE THREAD

**Issue by andrew-w-ross** [basarat/typescript-book#106]
In the section contributing under the section test categories it lists compiler tests and stops. Perhaps it should be expanded to include the other categories. Also how about describing how the tests work as they seem a bit cryptic.

**Comment by basarat** [comment]
> Perhaps it should be expanded to include the other categories. Also how about describing how the tests work as they seem a bit cryptic

All my learning is based on my observation as an external code reviewer. I took a week off last year to write / figure out what I could. I feel like I know enough to write developer tools using the compiler / language service (e.g. http://alm.tools/) and leave the compiler maintenance / contributing to other people .... at least for now :rose: 

As an example check out the syntax highlighting section for alm : https://basarat.gitbooks.io/alm/content/contributing/syntax.html  :rose:

**Comment by andrew-w-ross** [comment]
@basarat Thanks, this ebook has been the best explanation so far of the internals. But seeing an example project use the compiler services in depth is a big help.

**Comment by basarat** [comment]
> But seeing an example project use the compiler services in depth is a big help.

That would be alm. Feel free to ask any questions :rose:
