### ISSUE TITLE
Denote future features

### ISSUE THREAD

**Issue by trodi** [basarat/typescript-book#11]
Since this book is meant to be the definitive guide to TypeScript, developers ideally will read this when ramping up on TS as I did. In deploying a production system, you don't want to use an unreleased version of TS to get access to WIP features. You suggest getting the nightly build of TS as you are showing some future features. I would suggest that these future features (e.g., JSX, alt Type Assertion), should be marked as future to avoid confusion.

**Comment by basarat** [comment]
> I would suggest that these future features (e.g., JSX, alt Type Assertion), should be marked as future to avoid confusion.

Agreed. I added `(Note: you need typescript nightly for this at the moment).` to freshness https://github.com/basarat/typescript-book/blob/7d9a47f888922b1dee7f63b6c79cd3c6504e2d2f/docs/types/freshness.md 

Will go back and add to other sections that are still relevant post `1.5` release. Will close this issue once done :rose:

**Comment by basarat** [comment]
Most of these are now there with 1.6 released. Will be more mindful in future :rose:
