### ISSUE TITLE
Something to add to "export default can lead to problems"

### ISSUE THREAD

**Issue by khoomeister** [basarat/typescript-book#112]
https://github.com/basarat/typescript-book/blob/de784f994b6fc9a4cbe4910bd5b3de738f79012b/docs/tips/defaultIsBad.md

Using VS Code, "Find all references" on `import blah from 'blah2'` will only show references in local file (for now), whereas `import {blah} from 'blah2'` will show references across all files in the workspace.

BTW, thanks for the book!  Definitely helped me get up to speed with TS.

**Comment by basarat** [comment]
Thanks! This feels like a bug that should be fixed and might be fixed soon (needs to be reported to MS/TypeScript or MS/VSCode) so not adding it for now :rose:

**Comment by khoomeister** [comment]
Thanks, makes sense - not sure whether tsserver, vscode, etc. is the issue, but just filed an issue on the VSCode repo.
