### ISSUE TITLE
TypeScript never type 

### ISSUE THREAD

**Issue by basarat** [basarat/typescript-book#113]
PR : https://github.com/Microsoft/TypeScript/pull/8652 
Issue : https://github.com/Microsoft/TypeScript/issues/3076
Concept : https://en.wikipedia.org/wiki/Bottom_type

Add `bottom.md` in tips. 

# Use case 

```
// Without a bottom type we would error : 
// - Not all code paths return a value
// - Unreachable code detected
function foo(x: string | number) { 
  if (typeof x === "string") { 
    return true; 
  } else if (typeof x === "number") { 
    return false; 
  }
  fail("Unexhaustive!"); 
} 

function fail(message: string) { throw message; }
```

# Confusion with `void` 

`void` is a Unit. `never` is a falsum. 

A function that *returns* nothing returns a Unit `void`. However a function *that never returns* (or always throws) returns `never`. `void` is something that can be assigned (wihout strictNullChecking) but `never` can `never` be assigned to anything other than `never`.

**Comment by basarat** [comment]
Docs for the Never Type live here : https://basarat.gitbooks.io/typescript/content/docs/types/never.html :rose:

**Comment by Cryrivers** [comment]
i think the use case is not valid anymore. As I found that TypeScript doesn't infer `throw` or infinite loop to be bottom type `never` as the "return" value unless you explicitly declare it.

![image](https://user-images.githubusercontent.com/1313238/34402438-7cbece62-ebdc-11e7-939b-bae625bcb774.png)

**Comment by basarat** [comment]
The annotation needs to be explicit now : https://github.com/basarat/typescript-book/commit/fc3b4ca925dd094e35b0c237b34f14a5b00d3ba4 :rose: 

The default inference is now `void`.
