### ISSUE TITLE
Saying bind is Harmful is Bad since not using bind is even Worse

### ISSUE THREAD

**Issue by lenkite** [basarat/typescript-book#114]
https://javascriptweblog.wordpress.com/2015/11/02/of-classes-and-arrow-functions-a-cautionary-tale/

Methods get added to the class’s prototype which is where we want them — it means they’re only defined once, instead of once per instance. By contrast, class property syntax assigns the same properties to every instance. ie method functions will be redefined on every instance creation and not added to class prototype - highly inefficient.

**Comment by basarat** [comment]
> highly

Subjective. Also `bind` creates a new function in exactly the same way :rose:
