### ISSUE TITLE
Cannot find name ReadonlyArray

### ISSUE THREAD

**Issue by Taras-S** [basarat/typescript-book#117]
https://basarat.gitbooks.io/typescript/content/docs/types/readonly.html

This line: 
`let foo: ReadonlyArray<number> = [1, 2, 3];
`
Dont work in [TypeScript Playground](http://www.typescriptlang.org/play/index.html) and google dont know anything about "readonly typescript" too. Is this experimental feature or what?

I think, it will be better if there is will some text about this.

**Comment by basarat** [comment]
> Is this experimental feature or what?

Only in the latest builds https://basarat.gitbooks.io/typescript/content/docs/getting-started.html#typescript-version :rose:

**Comment by Taras-S** [comment]
I think you need to write about this in the chaper

PS: Awesome book, thank you.
