### ISSUE TITLE
Is the ePud outdated compared to the PDF?

### ISSUE THREAD

**Issue by jesperstarkar** [basarat/typescript-book#122]
ePud mentions tsd and PDF mentions typings in the same paragraph.

**Comment by basarat** [comment]
It built fine. 

I'll check when I am on a mac next :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/16533792/9a84df92-401e-11e6-843a-55c9f58e728e.png)

**Comment by basarat** [comment]
<img width="389" alt="screen shot 2016-07-13 at 3 06 12 pm" src="https://cloud.githubusercontent.com/assets/874898/16792399/6a0c84f0-490b-11e6-9ce3-884cce61acb6.png">

Seems fine in latest :rose:
