### ISSUE TITLE
Bind is Harmful > Class Members - This solution creates issues when extending

### ISSUE THREAD

**Issue by jamesbrobb** [basarat/typescript-book#125]
From [**Bind is Harmful**](https://basarat.gitbooks.io/typescript/content/docs/tips/bind.html)
```javascript
    class Adder {
        constructor(public a: string) { }

        // This function is now safe to pass around
        add = (b: string): string => {
            return this.a + b;
        }
    }
```

Above is the example you give for maintaining the scope of a function that's passed around as a callback. I've been using this style and it works as expected, but have come across a problem when trying to extend `Adder`:
```javascript
    class ExtendedAdder extends Adder {
        constructor(public a: string) { 
            super(a);
        }

        add = (b: string): string => {
            return super.add(b);
        }
    }
```
Firstly (and this is only a minor point), anyone extending `Adder` who wishes to override the `add` method, needs to ensure that they do so in the same style. Which i'm not sure is immediately obvious, so may be worth noting. Although the TS transpiler does give you the following error if you attempt to do this:

    error TS2425: Class 'Adder' defines instance member property 'add', but extended class 'ExtendedAdder' defines it as instance member function.

Secondly (and more importantly), which becomes clear why, from the previous error. Due to the fact this is a property declaration, as far as i can tell, it's not possible to override this style of method declaration and also make a call to `super`? The example given results in the following error:

    error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.

**Comment by basarat** [comment]
> it's not possible to override this style of method declaration and also make a call to super 

Possible, but not immediately obvious, I agree: 

```ts
class Adder {
	constructor(public a: string) { }

	// This function is now safe to pass around
	add = (b: string): string => {
		return this.a + b;
	}
}

class ExtendedAdder extends Adder {
	constructor(public a: string) {
		super(a);
	}

	private superAdd = this.add;
	add = (b: string): string => {
		return this.superAdd(b);
	}
}
```

:rose:

**Comment by jamesbrobb** [comment]
Thanks @basarat.

I'd thought of that (it's one style of inheritance that the team i currently work in, uses with JS), I'd just hoped it wouldn't be the only way to implement it with TS, as it feels like a step backwards.

**Comment by basarat** [comment]
Added documents : https://basarat.gitbooks.io/typescript/content/docs/arrow-functions.html#tip-arrow-functions-and-inheritance :rose:
