### ISSUE TITLE
Use monospaced font for code snippets.

### ISSUE THREAD

**Issue by ravshansbox** [basarat/typescript-book#152]

**Comment by basarat** [comment]
> Use monospaced font for code snippets

Definitely :rose:. Can you provide a screenshot / link where that is not the case?

**Comment by ravshansbox** [comment]
<img width="437" alt="untitled" src="https://cloud.githubusercontent.com/assets/1499188/17802218/656e8cb2-6608-11e6-9852-08cd101b7b57.png">
this is screenshot of epub version in iBooks app.

**Comment by basarat** [comment]
Yeah, the colored ones are off. I've sent a support request here : https://www.gitbook.com/contact :rose: Hopefully will get sorted
