### ISSUE TITLE
Capture the type of a string literal

### ISSUE THREAD

**Issue by basarat** [basarat/typescript-book#165]
Made possible in TypeScript 2.0 : http://danielearwicker.github.io/TypeScript_and_runtime_typing_EPISODE_II.html

Thanks @danielearwicker :rose:

**Comment by danielearwicker** [comment]
My pleasure - I have wanted `<T extends string>` to capture type since first playing with string literals in pre-release. Was very pleased to see it get into 2.0 rc.
