### ISSUE TITLE
Lost a line of code

### ISSUE THREAD

**Issue by ZenDay** [basarat/typescript-book#169]
In the chapter `generators` :

> The following example demonstrates `iterator.throw(error)`:
> 
> ```ts
> function* generator() {
>     try {
>         yield 'foo';
>     }
>     catch(err) {
>         console.log(err.message); // bar!
>     }
> }
> 
> var iterator = generator();
> // Start execution till we get first yield value
> var foo = iterator.next();
> console.log(foo.value); // foo
> // Resume execution throwing an exception 'bar'
> ```

Is it lost the line of code about throwing an exception 'bar'?

**Comment by basarat** [comment]
Correct! Fixed :rose:
