### ISSUE TITLE
Bind is bad

### ISSUE THREAD

**Issue by UppaJung** [basarat/typescript-book#179]
In the section title Bind is bad, you recommend using arrow functions in classes whenever you want "this" to refer to the object.

One problem with doing so is that you can't implement abstract methods this way.  I suppose you can implement an abstract method that calls a separate arrow method, but this seems less than ideal.  If that's the best option, please include it.  If there's a better option, it would be great to know!

**Comment by basarat** [comment]
Declare at as a property in the base: 

```
```
