### ISSUE TITLE
Organizing issue in a better way

### ISSUE THREAD

**Issue by djyde** [basarat/typescript-book#186]
Hi. **TypeScript Deep Dive** is a very nice book. I am really willing to be a contributor.

But I found the issues of this repo are too mess to contribute 🙈. So I have some suggestions:

1. Close the issue when that part of content has been completed.
2. Label some `help wanted` to tell the other who want to contribute that **you can write this part**

Thanks for your work! 🌹

**Comment by basarat** [comment]
Sorry for the late reply. Been travelling the past week to 🇲🇽 🇺🇸 but back now. 

I create a few issues just to benefit the *watchers* to get feedback on ideas. I leave them open for 

* Thinking about *where* to add them in the book 
* Thinking through if it is even a good idea 

The things that I know that I am still missing e.g. *decorators* I hold out on till it gets more stable (they are still subject to change).

I pick up issues when I have some downtime, i.e. time when I can't think of contributing to the world in any other meaningful way. The reason I don't mark as help wanted is that it only results in moving this relaxing task of maintaining a book into the reset of my OSS work where I review other code. 

That all said. I will start tagging help wanted for stuff that is *truly* low hanging :heart:

**Comment by basarat** [comment]
Indeed there are a few easy to review additions : https://github.com/basarat/typescript-book/labels/help%20wanted 🌹  😅

**Comment by djyde** [comment]
Cheers🌹
