### ISSUE TITLE
`Enum` should not be in `Future JavaScript`

### ISSUE THREAD

**Issue by djyde** [basarat/typescript-book#195]
The `Enum` type is not an ECMAScript draft. It's a part of TypeScript. So I don't think the enum doc should be in `future javascript`. @basarat How do you think about it?

**Comment by basarat** [comment]
Yeah. I felt bad about it. Move it into `types` :rose: 

# Long term thinking 

I plan to do a *big rewrite* at some point showing the *TS is Superset of JS* bit, mentioning the reasons why you might get errors (e.g. `function foo(){console.log(arguments)} foo(123)` ... valid JS and ts but error in a `.ts` file just like using a global variable without declaring is an error in a `.ts` file). And *then* not make the distinction of JS vs. TS. 

This book was written back when TS was not as widely accepted and had to show JS before true TS :rose:

**Comment by basarat** [comment]
been done :rose:
