### ISSUE TITLE
Guide for writing AST transformers

### ISSUE THREAD

**Issue by mohsen1** [basarat/typescript-book#218]
Now that https://github.com/Microsoft/TypeScript/issues/5595 is done, I'm assuming there is new API in LS that allows writing TypeScript to TypeScrtipt syntax transformers. Right now I'm trying to figure out how to write an TS to TS transformer function

**Comment by basarat** [comment]
No. There is no API like that on master yet. 🌹❤

**Comment by mohsen1** [comment]
Thanks for clearing that out! I thought Microsoft/TypeScript#5595 means now it's possible to write AST transformers using TS API. Do you know the ticket that tracks that issue?

**Comment by basarat** [comment]
For new syntax one needs additions to the parser + checker + emitter. The transformer only exist in the emitter.

> Do you know the ticket that tracks that issue

Nope :( :rose:

**Comment by mohsen1** [comment]
I think this is the issue: https://github.com/Microsoft/TypeScript/issues/10786

**Comment by basarat** [comment]
@mohsen1 thanks. I've subscribed. But it is just pretty printing the AST, not rewriting it. You can get the AST today as well but then *you* have the write the *complete* emitter. That issues doesn't change that fact. You still can't plugin to the transformers :rose:

**Comment by mohsen1** [comment]
If my transformer output standard typescript ast then I should be able to use existing emitter. No?

**Comment by basarat** [comment]
Yes. there is an `emitFile` function in emitter.ts that is public last I checked :rose:

**Comment by basarat** [comment]
Language service host to get custom transformer support : https://github.com/Microsoft/TypeScript/pull/13940 :rose:

**Comment by cancerberoSgx** [comment]
Here there are three working examples of using transformation API among other things:  https://typescript-api-playground.glitch.me/. 

BTW you can modify the code and run it again, have intellisense, etc. ...like a TypeScript Compiler API Playground.  I'm planning to put examples of different APis and libraries around TS compiler there hope it help newcomers - wouldn't be great to have similar tool to "describe" the API ? I've been inspired by monaco-editor playground which provided fast learning curve with its playground: https://microsoft.github.io/monaco-editor/playground.html
