### ISSUE TITLE
How to repeat a step in a chain of promises and how to recover from a failed step?

### ISSUE THREAD

**Issue by AlGantori** [basarat/typescript-book#260]
I am new to JS/TS and thus Promises, I managed to write my "Steps" as promises but I will take whatever construct you can outline. (working with ionic2/TS).

**How do I construct a chain of promises such that:**
 1. I can iterate over a chain of steps... 
 2. I can repeat Step2() say 5 times?
 3. Recover from Step1() failure and continue with next Index (all next steps).

Here is my current code outline
```
PlayAll() {

Step1(Index)
.then(() => {
console.log("PlayAll<<promise------------Step1 DONE");
  Step2(i)
  .then(() => {
      console.log("PlayAll<<promise------------Step2 DONE");
      if (Index < Count )
          Index++;
          ??? 
      else 
         if (typeof (this.Done) == "function")
           this.Done(); // a registered callback.
   }
  .catch(() => {
    console.log("Play<<promise------------Step2 FAIL");
    }
 }
 .catch(() => {
 console.log("Play<<promise------------Step1 FAIL");
 }
}
```
My Step1() looks like this
```
 // http://stackoverflow.com/questions/30069988/how-can-i-create-a-promise-for-the-end-of-playing-sound
    // 20160820
    PlayOne(Media: string) {
        console.log("AudioPlayList------------>>PlayOne Media is", Media);
        return new Promise((resolve, reject) => { // return a promise
            var audio = new Howl({ src: [Media] });                     // create audio wo/ src
            // cache a class level copy for other methods, eg. pause
            this.audio = audio;
            //

// not sure how to code reject here ???
// does this look correct?          
            // audio.on('error', () => {
            //     console.log("AudioPlayList<<e------------audio ERROR");
            //     reject(Media);
            //     return reject;
            // });      
                  
            audio.on('end', () => {
                console.log("AudioPlayList<<e------------audio ENDED");
                resolve(Media);
                return resolve;
            });                     // when done, resolve
            audio.play();
        });
    }
```

My Step3() not shown in the above outline looks like this
```
timer1: any;
  // https://www.typescriptlang.org/docs/release-notes/typescript-1.7.html
  // 20160812
  private SlidePostPause() {
    console.log("PlayAll------------>>PostPause");
    return new Promise<void>(
      resolve => {
        this.timer1 = setTimeout(resolve, this.Model.PostPause * 1000);
      });
  }
```
This link 
http://stackoverflow.com/questions/32032588/how-to-return-from-a-promises-catch-then-block
says
    _Returning a regular value from a reject handler, causes the next .then() resolve handler to be called (e.g. normal processing continues)_
which is what I typically want.

I have read your link 
https://github.com/basarat/typescript-book/blob/master/docs/promise.md
but I am still lost :)
Thank you for your help.

**Comment by basarat** [comment]
> Thank you for your help.

I really appreciate you reaching out for help here and considering me :rose: :heart:

That said, this issue tracker is not the right place. Best to post on Stackoverflow and ask for help there. Truly sorry that I don't have the time to look at the question right now so closing :rose:

**Comment by basarat** [comment]
> Recover from Step1() failure and continue with next Index (all next steps).

Wrap `step1` in something like 
```
new Promise(res => { 
  // try true step 1 multiple times and resolve if it succeeds or reject if you run out of count
})
```

Hope that helps :rose:
