### ISSUE TITLE
Suggestion: consider reference to typescript-string-enums

### ISSUE THREAD

**Issue by estaub** [basarat/typescript-book#261]
Simple unions as string-enums misses a lot of functionality.
Consider referencing https://github.com/dphilipson/typescript-string-enums
(I just found it recently and like it a lot.)

**Comment by basarat** [comment]
I think I've covered it a while back : https://github.com/basarat/typescript-book/blob/master/docs/types/literal-types.md#string-based-enums / https://basarat.gitbooks.io/typescript/content/docs/types/literal-types.html :rose:

Let me know if I missed something still :heart:
