### ISSUE TITLE
Nominal typing: typo or ambiguity?

### ISSUE THREAD

**Issue by estaub** [basarat/typescript-book#262]
In https://basarat.gitbooks.io/typescript/docs/tips/nominalTyping.html, I am puzzled by a word, and offer a change.  

Under `Using Enums`:

> Two enum types aren't equal if they differ by name. We can use this fact to provide nominal typing to any other type _that is structurally compatible_.

The way I read this (which is probably different from what you meant!) is as:

> Two enum types aren't equal if they differ by name. We can use this fact to provide nominal typing to any other type _that is structurally compatible_ **with enums**.

in which case I believe it should say structurally **incompatible**, not _compatible_. 

If it's correct as written, and my interpretation is wrong, maybe there's a way to make it clearer.

**Comment by basarat** [comment]
Hopefully this clarifies https://github.com/basarat/typescript-book/commit/a415249eb857dc2a53fbfc60c248ca6d8ad1d34d :rose:

**Comment by estaub** [comment]
Yes, great.  And great, great book!
