### ISSUE TITLE
arrow functions and inheritance

### ISSUE THREAD

**Issue by pjustino** [basarat/typescript-book#267]
Hi,

on the example in page 36 the add arrow function tries to add numbers as strings, so the following snippet will output 25 and not 7 as expected.

let add = new ExtendedAdder(2);
console.log("add result:" + add.add(5));  // output 25

**Comment by basarat** [comment]
Fixed https://github.com/basarat/typescript-book/commit/aa0f3ce33a20a2293cd4a06ed5b81e9fdb7eee86 :rose:
