### ISSUE TITLE
Cleaner Class property access (Question)

### ISSUE THREAD

**Issue by stherrienaspnet** [basarat/typescript-book#276]
Hello Basarat, i have a class property name fileUrl. I do not like the way i access it using self = this approach. I have probably miss a section on your book or maybe you have a better idea to do it cleaner. Here is my code:

import * as Promise from 'bluebird'

export class BinaryTypeWriter implements TypeWriter {
    private fileUrl: String;

    constructor(filePath: String) {
        this.fileUrl = filePath;
    }

    write(typeConfig: TypeConfiguration): Promise<Boolean> {
        const self:any = this;

        return new Promise<Boolean>(function (resolve, reject) {
            const writeStream = FileSystem.createWriteStream(self.fileUrl, defaults)
            writeStream ...
        });
    }
Thanks for your help!

**Comment by basarat** [comment]
Change `return new Promise<Boolean>(function (resolve, reject) {` to `return new Promise<Boolean>((resolve, reject) => {` and now you can use `this`. Covered here : https://basarat.gitbooks.io/typescript/content/docs/arrow-functions.html :rose: 

For questions : Prefer asking on stackoverflow and tweeting at me http://twitter.com/basarat if no one answers :heart:

**Comment by stherrienaspnet** [comment]
Thanks you very much!

Le 8 mai 2017 8:36 PM, "Basarat Ali Syed" <notifications@github.com> a
écrit :
