### ISSUE TITLE
String based enums

### ISSUE THREAD

**Issue by psumstr** [basarat/typescript-book#296]
@basarat In the section where you introduce string based enums and show a utility function to create key value pairs, why does the Typescript compiler not error out if I do the following:

```/** Utility function to create a K:V from a list of strings */
function strEnum<T extends string>(o: T[]): { [K in T]: K } {
  return o.reduce((res, key) => {
    res[key] = key;
    return res;
  }, Object.create(null));
}

/**
 * Sample create a string enum
 */

const directions = ['North', 'South', 'East', 'West'];

/** Create a K:V */
const Direction = strEnum(directions);
/** Create a Type */
type Direction = keyof typeof Direction;

/**
 * Sample using a string enum
 */
let sample: Direction;

sample = Direction.Northerns; // Why is this OK? 
```

The only difference is that we are passing an array of string to the function via a const named directions. When we do this, the type `Direction` appears to become an index signature `[key: string]: string`

**Comment by psumstr** [comment]
I thought a bit more about it and make sense to me now. The array literal initializes the array with the specified values as its elements, so it has a fixed length whereas the array of string can be dynamic if we later push values to it.

**Comment by basarat** [comment]
TS 2.4 RC just got string enums natively :rose: I'll update the book once I have time :heart:
