### ISSUE TITLE
Section "JavaScript > Making JavaScript Better"

### ISSUE THREAD

**Issue by marisev** [basarat/typescript-book#312]
> `{} + {}; // JS : NaN, TS Error`

Just wanted to note, `{} + {}` returns `NaN` in Firefox and IE. In Chrome it results in `"[object Object][object Object]"`.

**Comment by basarat** [comment]
Cheers https://github.com/basarat/typescript-book/commit/fd40b20da072c8e65b0dd1b5315bdf8bdcfc2ec2 :rose:
