### ISSUE TITLE
==

### ISSUE THREAD

**Issue by ShalokShalom** [basarat/typescript-book#316]
https://plus.google.com/+MatthiasSchusterScharmer/posts/fwrdqBz5UtW

**Comment by basarat** [comment]
People are free to use `foo === null || foo === undefined`. I just prefer `foo == null`. The character count diff for me is too significant. 

JSLint can ignore `==` when used with `null` OR people that use JSLint can write the longhand :rose: Thanks for the shout though :heart:

**Comment by ShalokShalom** [comment]
"The character count diff for me is too significant." You mean in a subjective sense?
