### ISSUE TITLE
Styleguide: All caps for const values?

### ISSUE THREAD

**Issue by nicojs** [basarat/typescript-book#335]
I get a lot of questions by students and colleagues about whether or not const values need to be ALL_CAPS like in Java. For example:

```typescript
const ALL_MESSAGES = ['work', 'init'];
```

I've seen this casing in some TypeScript projects as well (I think the angular team does it). 

The general javascript styleguide by crockford specifies to only use ALL_CAPS when it is a global variable (on the window/global object)

http://javascript.crockford.com/code.html

What should the general rule be? Or is it not in the scope of the styleguide?

**Comment by basarat** [comment]
Thanks for bringing this to my attention :heart:

`window.React` and `window.angular` don't follow this convention. Beyond that we personally shouldn't put anything on `window/global` so don't think its relevant anymore.

> I've seen this casing in some TypeScript projects as well (I think the angular team does it).

Would love to see it myself as well :rose:

**Comment by nicojs** [comment]
Thanks for your reply.

> `window.React` and `window.angular` don't follow this convention. Beyond that we personally shouldn't put anything on window/global so don't think its relevant anymore.

True about the crockford styleguide. Probably out-dated.

However, angular *does* use the ALL_CAPS casing style. Take this for example:

```typescript
export const PRIMARY_OUTLET = 'primary';
```

https://github.com/angular/angular/blob/master/packages/router/src/shared.ts#L18

You closed this issue. Does that mean that you don't want to voice an opinion about this in your style guide?

**Comment by basarat** [comment]
`const` like these are a bit special as many times they have external (non-javascript) dependencies. Sometimes I've done `const driverLicence = 'driver_licence'`. Some people would rather `const DRIVER_LICENCE = 'driver_license'`. I just keep my variable names consistent and would *personally* continue to encourage that, hence closing :rose:
