### ISSUE TITLE
TIP : Singleton

### ISSUE THREAD

**Issue by basarat** [basarat/typescript-book#34]
Ryan's answer : http://stackoverflow.com/questions/30174078/how-to-define-singleton-in-typescript

However I prefer to have them using a `once` wrapper utility function which allows singletons to be lazy.

https://github.com/TypeScriptBuilder/tsb/blob/48da91c68a1977aeaa665ca609b8cf86bc32ec71/src/common/utils.ts#L73-L83

```ts
export function once<T extends Function>(func: T): T {
    let ran = false;
    let memo = undefined;
    return function() {
        if (ran) return memo;
        ran = true;
        memo = func.apply(this, arguments);
        func = null;
        return memo;
    } as any;
}
```

**Comment by thefabulousdev** [comment]
I would also suggest considering showing  a more traditional OOP singleton implementation, seen in languages such as `C++`, which I believe a lot of developers might find easier to understand. 

```ts
class State {
    constructor(protected count = 0){

    }

    getCount(){
        return this.count;
    }
}

class ApplicationState {
    static state;
    static get(){
        if(!ApplicationState.state){
            ApplicationState.state = new State();
        }
        return ApplicationState.state;
    }
}
```

**Comment by basarat** [comment]
@thefabulousdev one of the goals of the singleton pattern is to prevent any mistaken duplicate instances. Your code doesn't prevent that as `new State(1);new State(2)` would be allowed. 

Of course it can be messaged to do the right thing but I will probably stick with Ryan's answer.

**Comment by thefabulousdev** [comment]
Whoops, I knew I had missed something, here's what I meant
```ts
class State {
    constructor(protected count = 0){

    }

    getCount(){
        return this.count;
    }
}

class ApplicationState {
    static state;
    constructor(){
        if(!ApplicationState.state){
            ApplicationState.state = new State();
        }
        return ApplicationState.state;
    }
}

var something = new ApplicationState();
var somethingElse = new ApplicationState();

console.log(something === somethingElse); // true
```
But its alright

**Comment by basarat** [comment]
> But I'm fine with your outcome.

Thanks :rose:

**Comment by basarat** [comment]
@thefabulousdev thanks. I've taken your feedback into account as well : https://basarat.gitbooks.io/typescript/content/docs/tips/singleton.html :rose:
