### ISSUE TITLE
defaultIsBad.md review

### ISSUE THREAD

**Issue by serbanghita** [basarat/typescript-book#350]
I read https://github.com/basarat/typescript-book/blob/master/docs/tips/defaultIsBad.md
Please take into the consideration my review.

> If you refactor Foo in foo.ts it will not rename it in bar.ts

This is a feature, if you refactor `Foo` locally in `foo.ts` there is **no impact** to the consumers of that class!

> If you end up needing to export more stuff from foo.ts (which is what many of your files will have) then you have to juggle the import syntax.

* import {myStaticMethod, default as SomeClass} from "./SomeClass";
* import SomeClass, {myStaticMethod} from "./SomeClass";

The fact that you need to update the import syntax is trivial and necessary. 
If you are going to use a new method/property/etc that is exported from `SomeClass` than you need to update the syntax anyway.

Is that syntax a problem generator?

> Bonus points: You even get autocomplete at this import {/*here*/} from "./foo"; cursor location. Gives your developers a bit of wrist relief.

This is not relevant to `export default`. When using `default` you **can only** expect the class `Foo` from `import Foo from "./foo";`

> Bonus points: Auto import quickfix works better. You use Foo and auto import will write down import { Foo } from "./foo"; caus its a well defined name exported from a module.

This is highly dependent on IDE. Is this what you are trying to say?
eg. IntelliJ knows when to autogenerate `import Foo` and `import {Foo}`

> Regarding the link title "Avoid Export Default"

If you read the current TypeScript documentation -
 section "Guidance for structuring modules" -
 https://www.typescriptlang.org/docs/handbook/modules.html#guidance-for-structuring-modules

> If you’re only exporting a single class or function, use export default
> 
> Just as “exporting near the top-level” reduces friction on your module’s consumers, so does introducing a default export. If a module’s primary purpose is to house one specific export, then you should consider exporting it as a default export. 

So in case I'm missing some major EcmaScript or TypeScript documentation update I don't see enough reasons to recommend avoiding `default export`.

**Comment by basarat** [comment]
My opinion is made up. You are entitled to disagree (or agree https://twitter.com/mweststrate/status/933728615841370114) and that is fine :rose:

**Comment by cyxou** [comment]
> ### Needs two lines for non-class / non-function
> 
> Can be one statement for function / class e.g. 
> 
> ```ts
> export default function foo() {
> }
> ```
> 
> But needs two statements otherwise:
> ```ts
> const foo = {
>   notAFunction: 'Yeah, I am not a function or a class',
>   soWhat: 'The export is now *removed* from the declaration'
> };
> export default foo;
> ``` 
This is not always true, as any object or value may be default-exported without assigning it to a variable like so (of course if you don't need to reference it within the file):

```ts
export default {
  notAFunction: 'Yeah, I am not a function or a class',
  soWhat: 'The export is now *removed* from the declaration'
};
```

**Comment by basarat** [comment]
> of course if you don't need to reference it within the file

Or add a type annotation: 

```ts
const foo: Foo = {
  notAFunction: 'Yeah, I am not a function or a class',
  soWhat: 'The export is now *removed* from the declaration'
};
export default foo;
```
Thanks for pointing it out though, I'll expand the section :rose:
