### ISSUE TITLE
The donate element is repeating

### ISSUE THREAD

**Issue by da1rren** [basarat/typescript-book#351]
It appears something funky is happening in Chrome 62. 

![image](https://user-images.githubusercontent.com/2702382/33614234-a58cb18a-d9ce-11e7-8599-bc467cfa4e0b.png)

After clicking around a few pages I start to see a build-up of the donate element.  I have replicated on two separate instances of chrome 62 without addons.

**Comment by basarat** [comment]
Not happening for me :(

**Comment by da1rren** [comment]
@basarat How odd.  It's not happening anymore...

I'm obviously just mad.

**Comment by basarat** [comment]
Screenshots don’t lie. So I can vouch for your sanity 🌹❤️

**Comment by basarat** [comment]
Repro gif https://twitter.com/fjaguero/status/943186357303828482

**Comment by da1rren** [comment]
@basarat It's being caused by UBlock origin.  You can see the dude has it installed.

**Comment by da1rren** [comment]
Yeah just replicated, with ublock it repeats when its disabled its fine.

**Comment by basarat** [comment]
@da1rren Thanks for pointing that out 🌹 x 💯 

Anyone using ublock feel free to send a PR to fix this code : https://github.com/basarat/typescript-book/blob/master/header.html (or send a PR to ublock? 🤷‍♂️ )

**Comment by kj-johnson** [comment]
I still get the duplication with uBlock disabled. In fact, I can get it to happen on Chrome, Firefox, Internet Explorer, and Edge.

All you have to do is mash the next-page button on the right side of the screen a few times in quick succession.

**Comment by buchmiller** [comment]
I can still get it to happen by clicking through a bunch of pages, then quickly pressing the back button a few times.

**Comment by basarat** [comment]
fixed :rose:
