### ISSUE TITLE
TypeScript venn diagram on “Your JS is TS” page is misleading

### ISSUE THREAD

**Issue by j-f1** [basarat/typescript-book#358]
This diagram:

> ![](https://raw.githubusercontent.com/basarat/typescript-book/master/images/venn.png)

implies that TS supports all JSNext proposals. However, it doesn’t support everything yet, so it might be helpful to mention that somewhere.

**Comment by basarat** [comment]
JSNext is open to interpretation. Leaving it out completely would scare away the ESNext loving folk :rose:

**Comment by karlhorky** [comment]
Yeah I would like to see some mention of the support (and philosophy behind it).

It seems like the current standard is Stage 3 of the TC39 process: 

https://github.com/Microsoft/TypeScript/issues/2103#issuecomment-182195915

https://www.reddit.com/r/typescript/comments/72k0x7/when_does_typescript_generally_support_new_js/

**Comment by basarat** [comment]
Thanks. Added :rose:

**Comment by karlhorky** [comment]
@basarat thanks! Just fixed some correctness, spelling and grammar errors: #506 

The [original commit](https://github.com/basarat/typescript-book/commit/0dd1e6bace619de125a37a0664380c1ea2adc75f) mentioned "TypeScript does add support for proposals till they reach stage-3", which is actually the opposite of what is correct :)
