### ISSUE TITLE
Typescript-book: Translations to Spanish and French

### ISSUE THREAD

**Issue by romero350** [basarat/typescript-book#372]
Greetings,

I would like to translate your book to Spanish and French so it can be more understandable for people limited by the english language. I would like to know how can I commit that translation to your repo. Also I would like to verify if your book has a Open Source license.

Thanks in advance for your answer.

**Comment by j-f1** [comment]
> Also I would like to verify if your book has a Open Source license.

It [looks like](https://github.com/basarat/typescript-book/blob/b098c6f75941bfb5f2b06190224f4aef1c81f1a2/LICENSE.md) it’s [CC BY](https://creativecommons.org/licenses/by/4.0/).

**Comment by basarat** [comment]
Added https://github.com/basarat/typescript-book/blob/master/README.md#translations Have at it :rose:
