### ISSUE TITLE
Type Guard section seems to have a problem

### ISSUE THREAD

**Issue by parker-mike** [basarat/typescript-book#377]
It states that `in` operator can be used as a type guard and gives an example that throws TS2339 with message "Property 'x' does not exist on type 'B'".

**Comment by basarat** [comment]
Make sure you are on ts latest :rose:

**Comment by parker-mike** [comment]
Oh, that's new in 2.7, didn't notice that, thanks!
Just one more question if I may, you guys say that it's a breaking change [(TypeScript Wiki on GitHub),](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#in-expressions-are-treated-as-type-guards) but the example given shows an obvious fact that since `foo` is always there, `else` will never be hit - what broke?
