### ISSUE TITLE
Typescript book translation to Filipino

### ISSUE THREAD

**Issue by themarshann** [basarat/typescript-book#379]
Hi,
I would love to contribute to the translation of this book in the Filipino language so it can have a wider reach. Will it be okay for me to do so?

Thanks in advance.

**Comment by basarat** [comment]
> book in the Filipino language so it can have a wider reach. Will it be okay for me to do so?

https://github.com/basarat/typescript-book/blob/master/README.md#translations added. Have it at and best of luck in your TypeScript journey :rose:
