### ISSUE TITLE
Tips on using language service to find references

### ISSUE THREAD

**Issue by jeffkhull** [basarat/typescript-book#395]
First of all, thank you for writing this invaluable guide!

Re: the AST section specifically [Here](https://github.com/basarat/typescript-book/blob/5a5a605a62d10bbf31a938327680e746d5a81bce/docs/compiler/ast-tip-children.md), would it be possible to also get an example of how to find references within a body of files of a given function declaration?  I am trying to build a dependency graph of function references across my codebase, and having a trouble reverse engineering uses of the functionality in the vscode codebase for example.

**Comment by basarat** [comment]
I will not cover the TS internals in a next iteration of this book so closing this for now :rose:

There might be a future seperate book on working with the compiler as an API :heart:
