### ISSUE TITLE
Move to vuepress now that the new gitbook is no longer open source and doesn't generate pdf or epub files

### ISSUE THREAD

**Issue by ghost** [basarat/typescript-book#398]
The new gitbook is not open source, nor does it generate epub/mobi/pdf files. If gitbook ever gets rid of the current "legacy view" all of their current features that are used may end up being useless.

We can replace the epub/mobi/pdf generation with a bash script that leverages pandoc.

**Comment by rogersachan** [comment]
See: https://github.com/GitbookIO/gitbook/issues/1808

**Comment by basarat** [comment]
Its migrated to gitbook v2. Not ideal but was minimum effort :rose:
