### ISSUE TITLE
'edit this page' links are broken

### ISSUE THREAD

**Issue by wmaurer** [basarat/typescript-book#41]
I wanted to make a quick fix to one of the pages: https://basarat.gitbooks.io/typescript/content/docs/types/ambient/d.ts.html#

However clicking 'edit this page' led me to a 404:
https://github.com/basarat/typescript-book/tree/master/en/docs/types/ambient/d.ts.md

Great book, BTW ;-)

**Comment by basarat** [comment]
> https://github.com/basarat/typescript-book/tree/master/en/docs/types/ambient/d.ts.md

Its inserting `en` for some reason (expected https://github.com/basarat/typescript-book/blob/master/docs/types/ambient/d.ts.md). I'll look into that :rose: :+1:

**Comment by basarat** [comment]
The link fixed itself `¯\_(ツ)_/¯` :) 

![image](https://cloud.githubusercontent.com/assets/874898/11645107/b3ed50c0-9da5-11e5-949b-aaf79b28dca5.png)

**Comment by wmaurer** [comment]
Yes it's also working for me now, thanks.
