### ISSUE TITLE
Excluding certain properties from the index signature does not work

### ISSUE THREAD

**Issue by PavelPZ** [basarat/typescript-book#410]
Example 
```
type FieldState = {
  value: string
}

type FormState =
  { isValid: boolean }
  & { [fieldName: string]: FieldState }
```

at the end of the [index-signatures](https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html) page does not for me.

See using ```FormState``` type TypeScript 2.9 in [playground](https://www.typescriptlang.org/play/#src=type%20FieldState%20%3D%20%7B%0D%0A%20%20value%3A%20string%0D%0A%7D%0D%0A%0D%0Atype%20FormState%20%3D%0D%0A%20%20%7B%20isValid%3A%20boolean%20%7D%0D%0A%20%20%26%20%7B%20%5BfieldName%3A%20string%5D%3A%20FieldState%20%7D%0D%0A%0D%0Aconst%20state%3A%20FormState%20%3D%20%7B%0D%0A%20%20isValid%3Atrue%0D%0A%7D) (TypeScript 2.9)

**Comment by basarat** [comment]
You can only use it to *read* some javascript object someone wrote e.g. 
```
type FieldState = {
  value: string
}

type FormState =
  { isValid: boolean }
  & { [fieldName: string]: FieldState }


// Use it for some JavaScript object you are gettting from somewhere 
declare const foo:FormState; 

const isValidBool = foo.isValid;
const somethingFieldState = foo['something'];

```

**Comment by basarat** [comment]
https://github.com/basarat/typescript-book/commit/870850422c22364888758e2bdce1b44065e51d98 :rose:
