### ISSUE TITLE
Declaration File page

### ISSUE THREAD

**Issue by wmaurer** [basarat/typescript-book#42]
From: https://basarat.gitbooks.io/typescript/content/docs/types/ambient/d.ts.html

> If a file has the extension .d.ts then each root level definition much have the declare keyword prefixed to it to make it clear that the author knows that there will be *no code emitted by TypeScript to ensure that this defined item will exist at runtime.* 

Do you mean "no code emitted by TypeScript **and** to ensure that this defined item will exist at runtime"?

**Comment by basarat** [comment]
@wmaurer thanks. I've made it clear:

> If a file has the extension .d.ts then each root level definition must have the declare keyword prefixed to it. This helps make it clear to the author that there will be no code emitted by TypeScript. The author needs to ensure that the declared item will exist at runtime.

:rose:

**Comment by basarat** [comment]
Long sentences. Was my bad :-)

**Comment by wmaurer** [comment]
:+1:
