### ISSUE TITLE
Provide a reference for statement about "large teams"

### ISSUE THREAD

**Issue by lazarljubenovic** [basarat/typescript-book#420]
https://github.com/basarat/typescript-book/blob/d4cbfa51ea4bd39c738e0dc114bab2d23fdb03b4/docs/why-typescript.md#L12

Could anyon find actual statements about this? **I** have no doubts that types improve code quality, or that companies have concluded this; but what about people that I need to convince about this? :smile:

Some links would be nice. I'll post here if I find some as well, but maybe someone else's got them or the author remembers?

**Comment by basarat** [comment]
Statement is based on public knowledge: 
* TypeScript is by Microsoft. 
* Google created Dart, and Use TypeScript (e.g. Angular Team)
* Facebook created FlowType and Use TypeScript (e.g. a few projects under github/facebook)

:rose:

**Comment by basarat** [comment]
Going to close this as there isn't an action here. Feel free to continue discussion :rose:
