### ISSUE TITLE
Another problem with export default?

### ISSUE THREAD

**Issue by dandv** [basarat/typescript-book#422]
It seems that `export default Foo` used in conjunction with [Dynamic imports()](https://developers.google.com/web/updates/2017/11/dynamic-import) also forces the developer to access all the exported properties through `.default`:

```js
const Highcharts = await import('https://code.highcharts.com/js/es-modules/masters/highcharts.src.js');
Highcharts.default.chart('container', { ... });  // Highcharts.chart is undefined
```

This actually happens with HighCharts ([fiddle](https://jsfiddle.net/dandv/16e7k0ta/11/)), for which named exports work fine if if [imported statically](https://jsfiddle.net/dandv/16e7k0ta/).

Would it be worth adding that to the [`export default` can lead to problems](https://basarat.gitbooks.io/typescript/content/docs/tips/defaultIsBad.html) page?

PS: thanks for making the book free!

**Comment by basarat** [comment]
Thanks :rose:
