### ISSUE TITLE
Incorrect statement regarding discriminated union types

### ISSUE THREAD

**Issue by jack-williams** [basarat/typescript-book#430]
Currently it says

_If using strictNullChecks and doing exhaustive checks you should return the `_exhaustiveCheck` variable (of type `never`) as well, otherwise TypeScript infers a possible return of `undefined`. So:_
```ts
function area(s: Shape) {
    switch (s.kind) {
        case "square": return s.size * s.size;
        case "rectangle": return s.width * s.height;
        case "circle": return Math.PI * s.radius * s.radius;
        default:
          const _exhaustiveCheck: never = s;
          return _exhaustiveCheck;
    }
}
```

Which isn't true. The switch gets marked as exhaustive so `undefined` is not included in the return type. This is fine:

```ts
function area(s: Shape): number {
    switch (s.kind) {
        case "square": return s.size * s.size;
        case "rectangle": return s.width * s.height;
        case "circle": return Math.PI * s.radius * s.radius;
    }
}
```

### Suggestion

Add a section talking about exhaustive switch statements, saying that typescript knows the code past the switch is unreachable so it will not add an implicit `undefined` to the return type.

**Comment by basarat** [comment]
> The switch gets marked as exhaustive so undefined is not included in the return type. This is fine:

Thanks for pointing that out. But will only work if you have an explicit return type and your return doesn't include optionals (aka undefined). Not general enough in my opinion :rose:

**Comment by basarat** [comment]
[Try this to see the error I speak of](https://agentcooper.github.io/typescript-play/#code/JYOwLgpgTgZghgYwgAgMoEcCucooN4BQyxyA1qACYBcyARAM5Y4S0DcRJ9wAXhDSJgC2AI2jsAvgQKhIsRCgBKEBGDggA5gBt8HYuRDU6uFWq0t2JZAHdgFMAAt+Q0VAsl7EYOvtgnIsQSSBAD0wWgA9oIQ4SAoAFaY9GDIcBQUEBTIDsD0yLFWyAAGAMLAUAjahcgAKgCeAA4QIWEA6ihW4ZiamZrApChg4cjayXWNqAhQwPXJ6sAAbihqyNBQ4VApyWq1yPWa8ln2cMkAVLEZ9CdZQwjH0Mgw64c50uDQ8EjIpeXayISW+kMtAQZQq5l0yCgqWAiT8LgkUjADRQqCOjWQAF40ExcMgAD7IJQmDS-AnfMHsAgwTAgFTAGIpXBwAAU9BoqLgjQAlH8IfQbGAEPZkKyAHSAnn-SwkW70FAMHEsGi4MCYKAgZD0UVcXjIK5anUQNzS5Cy+XGVQkpWQiCq9Wa0U2OzC-WijxeHzG6Vmuggn7WlVqjUAWWO9lFAAUAJJ6h1Qigw3Ku+OJr2WdLwLq+CEmhAxJLIAD6EAAHkdEmAFhBih4EKR+BBFhssfQvZJxEA)

**Comment by basarat** [comment]
<img width="514" alt="screen shot 2018-10-04 at 11 24 14 am" src="https://user-images.githubusercontent.com/874898/46447967-14bb3580-c7c8-11e8-8671-563a2eff82c2.png">

I've cleaned up the statement to be more accurate. Thanks again for pointing it out :rose:

**Comment by jack-williams** [comment]
Thanks for the quick response!
