### ISSUE TITLE
Wikibooks collaboration

### ISSUE THREAD

**Issue by rudolfolah** [basarat/typescript-book#434]
First, I love that this project uses a Creative Commons license!

Second, it would be neat to consider creating and moving the book over to [Wikibooks](https://en.wikibooks.org/wiki/Using_Wikibooks/Starting_A_New_Wikibook)

Wikibooks is similar to Wikipedia where anyone can collaborate and create a better book. Judging from all the issues so far (97 closed + 78 open), it seems like at least some of the parts of this book are perfect for collaboration. The advantage of Wikibooks is that pull requests are not blockers, edits can appear immediately, and discussion can be much more lively as each chapter can have its own discussion page.

Wikibooks has [instructions on donating an existing book](https://en.wikibooks.org/wiki/Wikibooks:Book_donations). This book fits in with their inclusion criteria (it would make an awesome textbook), and the licensing is related to the [GFDL (GNU Free Documentation License)](https://en.wikibooks.org/wiki/Wikibooks:GNU_Free_Documentation_License)

**Comment by basarat** [comment]
I want to keep it on github as it ties into the ecosystem I work with (devs) :rose:
