### ISSUE TITLE
Can i public the Chinese version of the book?

### ISSUE THREAD

**Issue by jkchao** [basarat/typescript-book#448]
Recently, an editor contact me, ask me if I want to publish [this book?](https://github.com/jkchao/typescript-book-chinese)
Because that book was translated according to your book, so i want get your consent.  if you agree, i will publish it. if you don't agree with it, of course i will not publish it.

**Comment by basarat** [comment]
Publish away. You have my consent. Translations are not easy to do. You deserve it :rose:

**Comment by jkchao** [comment]
thanks.

Can you give me  your contact information by email? If the book is published later, I will send a book to you.

**Comment by basarat** [comment]
sent :rose:
