### ISSUE TITLE
HTTPS error in website

### ISSUE THREAD

**Issue by basudebpalfreelancer** [basarat/typescript-book#454]
Hi Basarat,
Nice job with the website. Very nicely structured and concise theory with examples. Keep up the good work.
The issue I am having is with Chrome refusing to open the site showing HTTPS error as the HTTPS certificate seems to have expired for this site. So, every time I open the site, multiple steps need to be performed to view the content.
Thank you and best wishes,
Basudeb

**Comment by basarat** [comment]
It comes and it goes. Its managed by gitbook. Solution would be to move off it. Will try and do that sometime next year. 

https://github.com/basarat/typescript-book/issues/438

Thanks for raising it though :rose:
