### ISSUE TITLE
Is this accurate?

### ISSUE THREAD

**Issue by RevealedFrom** [basarat/typescript-book#457]
https://github.com/basarat/typescript-book/blob/master/docs/project/modules.md says:

By default when you start typing code in a new TypeScript file your code is in a global namespace. As a demo consider a file foo.ts:

    `var foo = 123;`

If you now create a new file bar.ts in the same project, you will be allowed by the TypeScript type system to use the variable foo as if it was available globally:

     `var bar = foo; // allowed`

If the default is everything is global, what is the setting that disables this?

**Comment by basarat** [comment]
There is no setting that disables it. Just be mindful and make sure you `export` something from the file / or import something. As soon as you `export` or `import` the file becomes a module :rose:

**Comment by RevealedFrom** [comment]
I tried to duplicate your code, but file bar.ts is unable to access `foo`.

**Comment by basarat** [comment]
>  but file bar.ts is unable to access foo.

You got a compile time error from TypeScript?

**Comment by RevealedFrom** [comment]
My mistake. I had an `export` in foo.ts. Like you said, as long as there is an `export` in a file, then the variables in that file are no more global. It's subtle.
