### ISSUE TITLE
React.SFC has been renamed to React.FunctionComponent

### ISSUE THREAD

**Issue by IanKemp** [basarat/typescript-book#461]
See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364

Docs that refer to `React.SFC` need to be updated to cater for this.

I'd be happy to make a PR for this, but not sure whether you want to put in a note that FunctionComponent was previously called SFC to prevent reader confusion, or just make the change.

**Comment by basarat** [comment]
Just made the change. Thanks for bringing to my attention! :rose:
