### ISSUE TITLE
sharing nominal type patterns

### ISSUE THREAD

**Issue by unional** [basarat/typescript-book#466]
I'm considering to add the `Id<T>` to my library `type-plus`.
Do you know if anyone has shared that in their packages?
If not, I would like to cite your name as the source.
Would that be ok for you? 🌷

**Comment by basarat** [comment]
> Do you know if anyone has shared that in their packages

Nope

> Would that be ok for you?

Always :rose: :heart: 💯 

# PS

⭐️ ed: https://github.com/unional/type-plus

**Comment by unional** [comment]
Thanks! Added: https://github.com/unional/type-plus/blob/master/src/Id.ts
