### ISSUE TITLE
PDF encoding is broken

### ISSUE THREAD

**Issue by Valve** [basarat/typescript-book#468]
Thank you for the book, it's helpful.

I'm using the PDF version in MacOS preview app. Two issues with the PDF:

1. Search not working. Try any word that should be there, returns zero results.
2. Encoding broken. I copy a fragment of code and paste it into VsCode and see this:

![screen shot 2019-01-24 at 3 35 49 pm](https://user-images.githubusercontent.com/27387/51710121-c25b8a00-1fed-11e9-8116-fdc08d1f951b.png)

**Comment by basarat** [comment]
We have a new pdf generator : https://github.com/basarat/typescript-book#other-options

Hopefully that fixed this :rose:
