### ISSUE TITLE
Promise chatper doesn't introduce needed package

### ISSUE THREAD

**Issue by Mati20041** [basarat/typescript-book#491]
First of all, this is a great book!

On the promise chapter I struggled with Promise class because it wasn't mentioned to add `@types/es6-promise` to `package.json`. I have found it by googling it.

Thanks again!

**Comment by basarat** [comment]
> On the promise chapter I struggled with Promise class because it wasn't mentioned to add `@types/es6-promise` to `package.json`.

Don't do that. Instead use the `lib` option:  https://basarat.gitbooks.io/typescript/content/docs/types/lib.d.ts.html#lib-option :rose:
