### ISSUE TITLE
Jest config example doesn't work

### ISSUE THREAD

**Issue by Flux159** [basarat/typescript-book#494]
Hi, I tried to use the jest.config.js from here: https://basarat.gitbooks.io/typescript/docs/testing/jest.html but jest was unable to find any files in my project directory. I'm using jest version 24.7.1

This is using a standard project with typescript files in a `/src/` directory and tests in `/__tests__/`.

Looking at the jest docs: https://jestjs.io/docs/en/configuration#roots-array-string, I updated my jest config to the following and was able to get it working:

```
module.exports = {
    verbose: true,
    roots: [
        "<rootDir>/src/",
        "<rootDir>/__tests__/"
    ],
    transform: {
      "^.+\\.tsx?$": "ts-jest"
    },
    collectCoverage: true,
};
```

It also seems like the `moduleFileExtensions` and `testRegex` fields aren't necessary anymore because jest added ts & tsx as default extensions and the default testMatcher now checks for ts files as well.

It might be helpful to update the book/docs incase someone else runs into this issue. Thanks!

**Comment by basarat** [comment]
Cheers ❤️ 🌹
