### ISSUE TITLE
TIP: Stateful Functions

### ISSUE THREAD

**Issue by si13b** [basarat/typescript-book#50]
Stateful functions as described are totally unnecessary in JS (and TS by extension). Since it has first-class functions it can easily be achieved with a closure:

```
const counter = (() => {
  let count = 0;
  return () => {
    count += 1;
    console.log(`Called : ${count }`);
  };
})();

counter(); // Called : 1
counter(); // Called : 2
```

https://github.com/basarat/typescript-book/blob/master/docs/tips/statefulFunctions.md

**Comment by basarat** [comment]
> Stateful functions as described are totally unnecessary in JS (and TS by extension). Since it has first-class functions it can easily be achieved with a closure

Thanks :rose:. However you are saying "not needed" followed by "here is how to do them". 

Also I do mention `using various abstractions that wrap over a local variable`. I didn't want to use the term closure to scare newbies :rose:. The pattern I present uses a closure too.

So comparison is between 

A.) 
```ts
const {called} = new class {
    count = 0;
    called = () => {
        this.count++;
        console.log(`Called : ${this.count}`);
    }
};
```
B.) 
```ts
const counter = (() => {
  let count = 0;
  return () => {
    count += 1;
    console.log(`Called : ${count }`);
  };
})();
```

I prefer A :rose: Also one could use `namespace`.

**Comment by si13b** [comment]
Yes, sorry, I didn't word that very well. They were two separate statements.

What I meant was the introduction of a "static" keyword would be unnecessary, as there's already a built-it feature capable of achieving the same thing and more.

I can understand that classes are easy to grasp for people coming from a OOP background. However, at run time they are actually functions, and they're an important concept to understand when working in a functional language.

As a suggestion, maybe mention them in passing if you want to avoid confusing the reader with a full example?

**Comment by basarat** [comment]
> and they're an important concept to understand when working in a functional language.

Agreed :rose: I probably need to add a complete section on JS Fundamentals. But didn't want to add that to this book in particular.
