### ISSUE TITLE
Type 'null' is not assignable to type 'number'

### ISSUE THREAD

**Issue by dchebakov** [basarat/typescript-book#507]
[At this section of the book](https://basarat.gitbooks.io/typescript/content/docs/types/type-system.html#null-and-undefined) said: 

> The null and undefined JavaScript ... These literals can be assigned to any other type. This is demonstrated in the below example
```
var num: number;
var str: string;

// These literals can be assigned to anything
num = null;
str = undefined;
```

but this example produce the error:
```
src/index.ts:6:1 - error TS2322: Type 'null' is not assignable to type 'number'.
6 num = null;
  ~~~
src/index.ts:7:1 - error TS2322: Type 'undefined' is not assignable to type 'string'.

7 str = undefined;
  ~~~
```

**Comment by dchebakov** [comment]
The error happened because I have enabled flag `strictNullChecks` in `tsconfig.json`

**Comment by basarat** [comment]
Thanks :rose: https://github.com/basarat/typescript-book/commit/464317153b7c9d54fbbb5dc6add743f4856507ff
