### ISSUE TITLE
Spread Operator: TypeScript compile error.

### ISSUE THREAD

**Issue by eiswind** [basarat/typescript-book#519]
function foo(x, y, z) { }
var args = [0, 1, 2];
foo(...args);

is valid javascript, but
actually does not compile in typescript.

let arguments: [number, number, number] = [0, 1, 2];
foo(...arguments);

does.

**Comment by basarat** [comment]
If you want to avoid the explicit type annotation you can use `as const`  :rose: 

```ts
function foo(x: number, y: number, z: number) { }
let args = [0, 1, 2] as const;
foo(...args);
```
