### ISSUE TITLE
What are Microsoft's "TypeScript StyleGuide and Coding Conventions" based on?

### ISSUE THREAD

**Issue by akopchinskiy** [basarat/typescript-book#520]
**Microsoft approach:**

```ts
// rocket.ts
export interface Rocket {
  fuel: number
  weight: number
}

export class Rocket implements Rocket {  // error: Duplicate identifier 'Rocket'
  fuel = 100;
  weight = 3000;

  launch(){
    console.log('launched!');
  }
}

export type Rocket = typeof Rocket; // error: Duplicate identifier 'Rocket' + unable to use type as value


// main.ts
import { Rocket } from './rocket.ts';     // error: Duplicate identifier 'Rocket'

const myRocket = new Rocket(); 
const myRocket2 : Rocket = {
  fuel : 50,
  weight : 2000
};  // Error: Type '{ fuel: number; weight: number; }' is missing the following properties from type 'Rocket': color, launch | ts(2739)
```

**Normal approach:**
```ts
// rocket.ts
export interface IRocket {
  fuel: number
  weight: number
}

export class Rocket implements IRocket {  
  fuel = 100;
  weight = 3000;

  launch(){
    console.log('launched!');
  }
}

export type TRocket = typeof Rocket; 


// main.ts
import { Rocket, IRocket } from './rocket.ts';  

const myRocket : IRocket = new Rocket(); 
const myRocket2 : IRocket = {
  fuel = 50,
  weight = 2000
};  // no errors
```

There is NO explanation why using prefixes, like "I", "T", "N" and others are bad.

**Comment by j-f1** [comment]
You typically wouldn’t have a class, interface, and type with the same name, and such a pattern is probably a code smell anyway.

**Comment by akopchinskiy** [comment]
@j-f1 I wonder where you got this from? Most developers use prefixes for interfaces and namespaces. Look for examples of C#.
Would like to hear more constructive arguments.

![image](https://user-images.githubusercontent.com/39277134/64118188-68971b80-cd97-11e9-9910-2b17e501084b.png)

**Comment by j-f1** [comment]
As I understand it, that is the style with C# but many TS developers don’t use the prefix. Additionally, the style guide included in this repo is not official.

**Comment by basarat** [comment]
> You typically wouldn’t have a class, interface, and type with the same name, and such a pattern is probably a code smell anyway.

I agree with this :100: 

Having a single noun per purpose is how I do naming. I would do something like `interface Rocket` and `class LaunchableRocket implements Rocket` based on what you have provided. Means you have to think more. If you disagree you are welcome to do `IRocket / Rocket` I wouldn't be against it :rose: 

The conventional case (different implementation for testing and production) I would do something like `Rocket / RocketProd / RocketMocked`.

**Comment by j-f1** [comment]
You could also do this:

```ts
class Rocket {
  // ...
}

class MockRocket implements Rocket {
  // ...
}
```
