### ISSUE TITLE
Paypal banner blocks typography button on mobile

### ISSUE THREAD

**Issue by zcdunn** [basarat/typescript-book#530]
I'm using Firefox on a Moto G6. The "buy me a beer/coffee" link blocks the typography button at the top of all pages. The typography button is displayed, but trying to click on it activates the paypal link. This means I can't switch to dark mode and increase the font size, so I'm not able to read the book on mobile.

**Comment by basarat** [comment]
Your experience is valid. However the button isn't clickable even if I delete the donation button: 

![image](https://user-images.githubusercontent.com/874898/67799064-c6ff2280-fad8-11e9-9354-48676c6b4296.png)


How the donation button is added : https://github.com/basarat/typescript-book/blob/158eabf9eda0f7ff65a7953006fa994a920846be/header.html#L4

You can remove it in the rendered dom and see that the typography button still becomes unclickable even without the donate banner. Gitbook bug :rose:

**Comment by basarat** [comment]
There is no paypal banner anymore :rose:
