### ISSUE TITLE
No syntax highlight for some code blocks in Promise section

### ISSUE THREAD

**Issue by rruc** [basarat/typescript-book#535]
I've noticed that some code blocks in [Promise/Callback style code](https://basarat.gitbooks.io/typescript/content/docs/promise.html) have no syntax highlight. [Markdown](https://github.com/basarat/typescript-book/blob/master/docs/promise.md#callback-style-code) looks fine to me though.

**Comment by basarat** [comment]
Seems to be fixed after upgrade to gitbook v2 : https://basarat.gitbook.io/typescript/future-javascript/promise :rose:
