### ISSUE TITLE
A desctructing example need awesomenized

### ISSUE THREAD

**Issue by Gfast2** [basarat/typescript-book#537]
Hi @basarat ,

I'm reading this awesome book right now, I've start to considering make donation later on.

When I reading this example: 

```javascript
var foo = { bar: { bas: 123 } };
var {bar: {bas}} = foo;
``` 

I tried it with `console.log(bar); console.log(bas); ` naturally. This cause issue, because this destructing statement only desctruct `bas` only, it only looks like it desctruct them both. 

Would it be better to desctructing them both for clarity like the following:
 
```javascript
var foo = { bar: { bas: 123 } };
var {bar, bar: {bas}} = foo;
``` 

**P.s.**: if it make sense to you, I can make a pull request, just tell me here!

**Comment by basarat** [comment]
Thanks for the kind words! 🌹

I’ll stick with the single concept example that is already there 👍🏻

**Comment by Gfast2** [comment]
Hi @basarat 
Fair enough & Thank you for your fast reply! 💇
