### ISSUE TITLE
Conflicting advice regarding comparison with null vs. undefined

### ISSUE THREAD

**Issue by joebowbeer** [basarat/typescript-book#544]
`== null` is recommended on this page:

https://basarat.gitbooks.io/typescript/content/docs/javascript/null-undefined.html

`== undefined` is recommended in style guide:

https://basarat.gitbooks.io/typescript/content/docs/styleguide/styleguide.html#null-vs-undefined

**Comment by basarat** [comment]
Thanks for catching that. My opinion has changed over time after trying different approaching in the real world :rose:
