### ISSUE TITLE
Dark theme/font size options no longer available

### ISSUE THREAD

**Issue by mokyox** [basarat/typescript-book#549]
Hi there.

I was using the book a few weeks ago and I remember seeing a dark/dark blue mode and options for different text sizes. However I cannot see any of those options on Chrome, Firefox and Safari.

Here is how it looks now - no formatting options that I can see.

<img width="1357" alt="Screen Shot 2020-01-05 at 21 13 22" src="https://user-images.githubusercontent.com/23492964/71786243-3c1f3480-3001-11ea-9a7a-ecd3daa05c5c.png">

Could it be an issue with the recent move to the gitbooks new? https://github.com/basarat/typescript-book/commit/b7a9db4364f25aa359bbae61bf32eafae47ca719

Thank you.

**Comment by basarat** [comment]
> Could it be an issue with the recent move to the gitbooks new? 

Yes. Gitbook old will be no more sometime this year so wasn't an option, had to migrate :rose:

Closing as nice feature request but really a feature request for gitbook :heart:
