### ISSUE TITLE
Gitook to Ebook Mobi PDF

### ISSUE THREAD

**Issue by watkinsmatthewp** [basarat/typescript-book#550]
When I click the EPUB / MOBI links on the site, legacy GitBook just redirects me back to your homepage. Could you maybe attach the downloadable ebook files as a release on this repo?

**Comment by lukesdm** [comment]
Looks like *all* old links no longer work e.g. the top link from google search results for "jest typescript" points to `https://basarat.gitbooks.io/typescript/docs/testing/jest.html`, which redirects to homepage.

**Comment by basarat** [comment]
It is what it is (not ideal - indeed bug - but out of our control) : https://twitter.com/basarat/status/1213810047924494336 :rose:

**Comment by watkinsmatthewp** [comment]
I was really hoping to put this on my Kindle. Do you have a mobi or epub file you can attach if Gitbook won't generate one?

**Comment by aristofun** [comment]
Meanwhile would appreciate a lot working links to PDF/ePub versions...

**Comment by basarat** [comment]
some docs from 2016 : https://github.com/GitbookIO/gitbook/blob/master/docs/ebook.md don't know if its gitbook v2 (looks like it is). I read it but don't know how to proceed. Help wanted :rose:

**Comment by willsp** [comment]
I created the ebooks using the linked instructions.

* [typescript-book.pdf](https://github.com/basarat/typescript-book/files/4061728/typescript-book.pdf)
* [typescript-book.zip](https://github.com/basarat/typescript-book/files/4061732/typescript-book.zip) (contains epub and mobi)

**Comment by basarat** [comment]
looks great thanks 😊
Does it need a Mac?
If there are just bash commands that you can provide then I can setup Travis to do this on each commit 🌹❤️

**Comment by willsp** [comment]
Doesn't necessarily needed a mac, but it does need a binary from Calibre.
I'll send the commands I ran over tomorrow.

**Comment by watkinsmatthewp** [comment]
> I created the ebooks using the linked instructions.
> 
> * [typescript-book.pdf](https://github.com/basarat/typescript-book/files/4061728/typescript-book.pdf)
> * [typescript-book.zip](https://github.com/basarat/typescript-book/files/4061732/typescript-book.zip) (contains epub and mobi)

Not all heroes wear capes :)

**Comment by willsp** [comment]
Okay, so first you gotta figure out how to get ebook-convert (a binary from [calibre](https://calibre-ebook.com/)) onto the Travis server and put it in the PATH. At that point, it's just 1 command to create each ebook.

```
# From the root of the package
gitbook mobi ./ ~/temp/typescript-book.mobi
gitbook epub ./ ~/temp/typescript-book.epub
gitbook pdf ./ ~/temp/typescript-book.pdf
```

**Comment by windix** [comment]
I have created a github actions to generate ebooks in different formats. 
For the example you can refer to my github actions: 
https://github.com/windix/typescript-book/actions/runs/33901218

**Comment by basarat** [comment]
From https://github.com/basarat/typescript-book/pull/558 build should be happening 💯 (thanks @windix 😘 ): 

Happy to take PRs to update links / any other improvements people want for the artifacts :rose:

**Comment by windix** [comment]
@basarat I have added a PR #560 , please check 💪

**Comment by windix** [comment]
So after discussing with @basarat , I think the current ebook build per commit on master branch (as artifacts in github actions) is probably the best solutions. We may just need to update the README to let everyone know where to find them.

Note that the artifacts will be expired (deleted) after 90 days (https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts). Assume we won't need to wait for more than 90 days to have at least one new commit on master 😄

**Comment by zero-t4** [comment]
> So after discussing with @basarat , I think the current ebook build per commit on master branch (as artifacts in github actions) is probably the best solutions. We may just need to update the README to let everyone know where to find them.
> 
> Note that the artifacts will be expired (deleted) after 90 days (https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts). Assume we won't need to wait for more than 90 days to have at least one new commit on master 😄

So when new files will be available? After one merge in master?

**Comment by basarat** [comment]
https://github.com/basarat/typescript-book#other-options :rose:

**Comment by magrega** [comment]
still not accessible. Can someone help me get a russian translated book?
