### ISSUE TITLE
AN_ISSUE_ABOUT_ISSUES

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [basarat/typescript-book#552]
Funnily, I only today remark that there always has been an "issue" section for every repo.

And there is no "thank you" section.

Meaning that thank yous are un-useful? I highly doubt that,so it is an issue, that there is no thank you section.

And thank you for the effort put in this book, which I appreciated reading some part of.

**Comment by basarat** [comment]
> thank you for the effort put in this book, which I appreciated reading some part of.

❤️ 💯 :rose:

> And there is no "thank you" section.

Leave a star : https://github.com/basarat/typescript-book/stargazers ;) 

![image](https://user-images.githubusercontent.com/874898/72876147-f628d700-3d49-11ea-93f8-c8bb4ad567c8.png)
