### ISSUE TITLE
tweak nodemon + ts-node for better DX

### ISSUE THREAD

**Issue by antonk52** [basarat/typescript-book#556]
In the [nodejs example](https://github.com/basarat/typescript-book/blob/master/docs/quick/nodejs.md) it is suggested to use a script
```
nodemon --watch 'src/**/*.ts' --exec 'ts-node' src/index.ts
```
which is ok when starting a project, but as the project grows it really starts to show. I was wondering if there is a thought behind it? Why not use [`ts-node-dev`](https://www.npmjs.com/package/ts-node-dev) which handles file changes for you or a tweaked usage of the script in the example such as `tsc --watch & nodemon dist/index.js`? Latter one works faster in my experience. I am happy to do a PR for this but I wanted to ask about it beforehand. Thanks!

**Comment by basarat** [comment]
I love ts-node-dev : https://www.youtube.com/watch?v=Hi-ShZ5ShkE :rose:
Post a PR and @basarat me so it comes in my inbox :heart:
