### ISSUE TITLE
readonly - difference from const - formatting wrong on gitbook

### ISSUE THREAD

**Issue by rtpHarry** [basarat/typescript-book#557]
Compare:

https://github.com/basarat/typescript-book/blob/master/docs/types/readonly.md#difference-from-const

To:

https://basarat.gitbook.io/typescript/type-system/readonly#difference-from-const

List is not formatted on gitbook:

![image](https://user-images.githubusercontent.com/1038062/73601337-a58a5880-4557-11ea-9f7b-312ae12dfc82.png)

**Comment by basarat** [comment]
Thanks :rose:
