### ISSUE TITLE
get started link broken

### ISSUE THREAD

**Issue by Xanhou** [basarat/typescript-book#567]
The get started link points to gitbook**S**.io, which does not seem to work.
If I manually change this to gitbook.io, it seems to work just fine.
Is this actually a broken link, or is gitbooks.io just having trouble?
Full current link:
http://basarat.gitbooks.io/typescript/content/docs/getting-started.html
Full working link:
http://basarat.gitbook.io/typescript/content/docs/getting-started.html

**Comment by basarat** [comment]
Thanks. Fixed https://github.com/basarat/typescript-book/commit/9c429a9ec8d836a68b5acb4f1955ea22fc51c2bb 

This was done gitbooks due to their infrastructure changes (v1 -> v2) :rose:
