### ISSUE TITLE
TypedEvent alternative

### ISSUE THREAD

**Issue by binier** [basarat/typescript-book#580]
Unless target platform isn't NodeJS, creating custom class with custom implementation just to get type-checking is probably overkill.

Current implementation:
- is limited, since by design it allows only one event per emitter.
- supports only 1 passed argument to `emit` and `listener`.
- might introduce bugs because of custom implementation like it did before: #405, #516.

Wouldn't it be better if we simply define custom typings for the existing EventEmitter implementation and export it? Wrote small [library](https://github.com/binier/tiny-typed-emitter) that does just that.

Sample:
```
import { TypedEmitter } from 'tiny-typed-emitter';

interface MyEvents {
  'added': (el: string, wasNew: boolean) => void;
  'deleted': (deletedCount: number) => void;
}

const ee = new TypedEmitter<MyEvents>();

ee.emit('added', 'el', true);
ee.on('added', (el, wasNew) => console.log(el, wasNew));

ee.emit('deleted', 5);
ee.on('deleted', (count) => console.log(count));
```

**Comment by basarat** [comment]
It wasn't meant as an implementation you must / should use. Was based on a discussion on what you should look for when using TypeScript.

Thanks for sharing your implementation though :rose:
