### ISSUE TITLE
Cypress with typescript: Creating Page Object Tips 

### ISSUE THREAD

**Issue by rachitpuri95** [basarat/typescript-book#586]
Hey, 
If I want to specify a return object for the page object getters, How can I achieve this in typescript. 
For example: 

```
class LoginPage {
  get username(): Chainable<Subject> { // compiler is unable to find chainable here. 
    return cy.get(`#${Ids.username}`);
  }
```

**Comment by basarat** [comment]
Ensure `types` in `tsconfig.json` has `cypress` in it. See : https://www.youtube.com/watch?v=n3SvvZSWwfM :rose:
