### ISSUE TITLE
 Epub, Mobi, and PDF formats are not generated anymore

### ISSUE THREAD

**Issue by ronaldborman** [basarat/typescript-book#610]
During the last builds the step 'Run gitbook install' was not successful so the build failed and subsequent steps were skipped. The returned error is `TypeError: cb.apply is not a function` at `FSReqCallback.oncomplete`.

As a result the Epub, Mobi, and PDF formats are not generated anymore with Github Actions.

**Comment by jtcmedia** [comment]
This appears to be an issue with gitbook-cli: https://github.com/GitbookIO/gitbook-cli/issues/110.
It has a dependency on an older version of graceful-fs where this problem hasn't been resolved for Node 12. gitbook-cli is [deprecated](https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning) so this won't get fixed but judging from the comments, it looks like there is an effort to maintain a fork of it. I modified the build script in this repo to downgrade to Node 10 and built the books [here](https://github.com/jtcmedia/typescript-book/actions/runs/300817690).

**Comment by wilitp** [comment]
I made a Dockerfile that builds and image containing the output in `/output/`.
```dockerfile
FROM node:10

RUN apt update
RUN apt install calibre-bin -y
RUN npm install -g gitbook-cli
WORKDIR /app/
COPY . .

RUN gitbook install
RUN mkdir /output

RUN gitbook mobi . /output/typescript-book.mobi`
```

Just make sure that the context for the image build is the root of the book's repo.

**Comment by geekdenz** [comment]
Built the book just now from master:

https://drive.google.com/drive/folders/1kBv2xzKssiQfrR6PED8rWPS2IFcoxGU6?usp=sharing

Hoping to make someone's life easier...

**Comment by alexsivris** [comment]
Using honkit to build the latest version: https://github.com/honkit/honkit

1. Install calibre (on MacOS via homebrew: `brew install --cask calibre`)
2. Install honkit in local book path: `npm i -D honkit`
3. Install required plugins: `npm i -D gitbook-plugin-edit-link gitbook-plugin-github gitbook-plugin-adsense gitbook-plugin-header`
4. Build the book in a format of your choice, e.g.`npx honkit epub` or `npx honkit pdf` -> the generated book will be saved in the root repo path as `book.epub`/`book.pdf`.

Or if you rather want to use a docker container you can create a local image:
```
FROM honkit/honkit:latest

RUN npm install -g gitbook-plugin-edit-link gitbook-plugin-github gitbook-plugin-adsense gitbook-plugin-header
```
and then run ```docker run -v `pwd`:`pwd` -w `pwd` --rm -it local-honkit honkit pdf```
