### ISSUE TITLE
All actions/builds are failing. Cannot download .epub version.

### ISSUE THREAD

**Issue by vettukal** [basarat/typescript-book#661]
It was mentioned that epub files can be downloaded from artifacts section. 
![image](https://user-images.githubusercontent.com/1246832/157332487-0bef4d86-9c66-43a7-8922-a1b56ca009ad.png)

But all the builds are failing. 
![image](https://user-images.githubusercontent.com/1246832/157332660-c00a4382-76e6-415b-8b95-6a838097e269.png)

**Comment by icodeforyou-dot-net** [comment]
my words exactly

**Comment by divyanshyadav** [comment]
Same here

**Comment by santakd** [comment]
Cannot download PDF version of the ebook
The recent builds have failed and the last few successful builds have expired links

**Comment by basarat** [comment]
Thanks for the ping. I found and merged a PR that hopefully fixes it 🤷🏻  https://github.com/basarat/typescript-book/pull/653 
Feel free to ping me if it doesn't work and anyone sees a better PR :rose:

**Comment by snaeil** [comment]
Does still/again not work now, right?

**Comment by let-robots-reign** [comment]
Can confirm, unfortunately it doesn't work again

**Comment by snaeil** [comment]
@basarat Do you know whether this can be fixed again?

**Comment by iliakan** [comment]
Artifacts expired =(

**Comment by kutsan** [comment]
Friendly ping @basarat.
