### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by SteveALee** [basarat/typescript-book#68]
A really good read. Thank you.

* Could you add an example for browser using browserify?
* You suggest using `-module system` but in the node and browser sections you don't use it. Why?
* How do we use ESLint etc with typescript?
* Can we use Typescript as a replacement for Babel and then start to add type info over time

**Comment by basarat** [comment]
> A really good read. Thank you.

Thanks! :rose:

> Could you add an example for browser using browserify?

Could. But this book has opinions. I try not to give the user too many options and then make it their problem to figure out which one is the right one for them. `webpack` is defacto in the React Ecosystem. `system` is defacto in Angluar Ecosystem. I don't see many teams using browserify at scale. 

>  How do we use ESLint etc with typescript?

You would use tslint :rose:

> Can we use Typescript as a replacement for Babel and then start to add type info over time

Can if you are not using `async` / `generators`.

> You suggest using -module system but in the node and browser sections you don't use it. Why?

That was the recommendation coming out of the community I was surrounded by at the time. Since then I have gone for simplicity aka NPM all things https://medium.com/@basarat/friends-don-t-let-friends-use-bower-380bba84111a#.2mirkyjop

I've updated the docs in the attached commit :rose:

**Comment by SteveALee** [comment]
You might be right about browserify and scale. I appreciate it's simpler approach to bundling and commonJS module use in browsers and don't really need all the bell's and whistles Webpack now offers.

I saw TSLint in my searches and i certainly covers the basics needed for linting and style checking. It would be so much better if the main programs like ESLint supported TS, then we could easily adopt the community formats like AirBnB's witxh some tweaks for TS.

Yeah,  I love NPM too (especially for build). I'm not sure it's tied to CommonJS though - isn't that more nodejs at the moment. Surely modules can use ES6 imports as well?

**Comment by basarat** [comment]
> You might be right about browserify and scale. I appreciate it's simpler approach to bundling and commonJS module use in browsers and don't really need all the bell's and whistles Webpack now offers.

Sure. The whistles include stuff like lazy loading `require.ensure` that turn up faster than you might think in a web app. 

> I saw TSLint in my searches and i certainly covers the basics needed for linting and style checking. It would be so much better if the main programs like ESLint supported TS, then we could easily adopt the community formats like AirBnB's witxh some tweaks for TS.

Indeed. But it needs the ESLint parser to support TS syntax which is not true yet. 

> Yeah, I love NPM too (especially for build). I'm not sure it's tied to CommonJS though - isn't that more nodejs at the moment. Surely modules can use ES6 imports as well?

No. Browsers don't understand ES6 imports at the moment. You need a module loader e.g. SystemJs. I say drop the hassel and just use commonjs everywhere + webpack to bundle for frontend. See http://alm.tools/ for a working example :rose:

**Comment by joebowbeer** [comment]
> You would use tslint 🌹

These days you would use typescript-eslint?

https://github.com/palantir/tslint/issues/4534

**Comment by basarat** [comment]
Yup : https://basarat.gitbooks.io/typescript/docs/tools/eslint.html

**Comment by tmiquel** [comment]
> No. Browsers don't understand ES6 imports at the moment. You need a module loader e.g. SystemJs. I say drop the hassel and just use commonjs everywhere + webpack to bundle for frontend.

These days, would you still use `module:commonjs` in tsconfig.json and use the ES module syntax to import / export / author modules as you wrote [there](https://basarat.gitbook.io/typescript/project/modules/external-modules#clarification-commonjs-amd-es-modules-others). Or switch to Es modules? Just learning and curious to know your thoughts on this

**Comment by basarat** [comment]
> Just learning and curious to know your thoughts on this

Currently I bundle both when its worth the effort e.g. TypeStyle : (commonjs : https://github.com/typestyle/typestyle/blob/master/tsconfig.json + ES2015 https://github.com/typestyle/typestyle/blob/master/tsconfig.es2015.json)

For most things I just do commonjs only. There are still worse (JS) things out there :rose:
