### ISSUE TITLE
__extends. One more detail

### ISSUE THREAD

**Issue by rzaitov** [basarat/typescript-book#71]
[Here](https://basarat.gitbooks.io/typescript/content/docs/classes-emit.html) you explain what does \__extends do. You mentioned that it is effectively does the following:
`d.prototype.__proto__ = b.prototype`

From my point of view it is worth to mention why it doesn't do this directly. When I read that first time I was wondering "Why it is so compicated? Why we just can't `d.prototype.__proto__ = b.prototype`"

My guess that old browsers doesn't support \__proto__ property (as you mentioned). I mean that it is more safe.

Thanks for the excellent book!

**Comment by basarat** [comment]
Thanks! Will keep it as it is for now in the absence of a concrete reorganisation 🌹
