### ISSUE TITLE
suggestion: Iterators

### ISSUE THREAD

**Issue by andruhon** [basarat/typescript-book#81]
It would be nice to have a chapter describing iterators (with iterator symbol) specific with TypeScript. It is quite straight forward, we're just need to define proper type as it expressed in https://github.com/Microsoft/TypeScript/blob/master/src/lib/es6.d.ts, but still good to have as a separate chapter.

**Comment by basarat** [comment]
Cheers. Leaving open for myself :rose:

**Comment by andruhon** [comment]
May I contribute a draft for that?

**Comment by basarat** [comment]
> May I contribute a draft for that?

go for it :heart:

**Comment by basarat** [comment]
Done. Thanks @andruhon again :rose:

**Comment by andruhon** [comment]
You're welcome. Thank you for helpful book.
