### ISSUE TITLE
dead link in "iterators" section

### ISSUE THREAD

**Issue by ZuBB** [basarat/typescript-book#86]
"interfaces" below is a link which point to https://basarat.gitbooks.io/typescript/content/types/ambient/interfaces.md and its says 404

> Again. Iterator itself is not a TypeScript feature, this code could work without implementing Iterator and IteratorResult interfaces explicitly. However it is very helpful to use these common ES6 **interfaces** for code consistency.

**Comment by basarat** [comment]
Thanks. Should be fixed now :rose:
