### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by pitosalas** [basarat/typescript-book#9]
"If you now create a new file bar.ts in the same project, you will be allowed by the TypeScript type system to use the variable foo as if it was available globally:" 

From the section on modules. What does it mean to say "in the same project"? Under the same tsconfig.json? So a project is parsed and reports named conflicts / allows sharing across files? Which implies a --out? Which in turn is actively discouraged? 

It might be good to clarify that sentence along those lines. Thanks.

**Comment by basarat** [comment]
> Under the same tsconfig.json

Yes.

> So a project is parsed and reports named conflicts / allows sharing across files

yes

> which implies a --out

No. Not unless you explicilty *rely on `--out`*. The global namespace is still useful for external libraries (e.g. jquery definitions). 

> Which in turn is actively discouraged

Yes. 

> It might be good to clarify that sentence along those lines.

I'll do that :rose:

**Comment by basarat** [comment]
I've moved `tsconfig.json` docs to the top so that `in the same project` is clear.

**Comment by pitosalas** [comment]
Also, though, I think the term “project” or “in the same project” is never really defined. 

— Pito

On July 10, 2015 at 7:00:13 PM, Basarat Ali Syed (notifications@github.com) wrote:

I've moved tsconfig.json docs to the top so that in the same project is clear.

**Comment by basarat** [comment]
> Also, though, I think the term “project” or “in the same project” is never really defined.

I realized that and did that in the same push referenced above. Screenshot: 

![image](https://cloud.githubusercontent.com/assets/874898/8630774/51e4b652-27ad-11e5-92f1-da78603fdc81.png)

Thanks for your feedback :rose:
