### ISSUE TITLE
readonly modifier is not currently supported

### ISSUE THREAD

**Issue by mikle111** [basarat/typescript-book#91]
`readonly` is planned to 2.0

**Comment by basarat** [comment]
Indeed. This book covers typescript nightly whenever possible as mentioned in getting started 🌹

**Comment by basarat** [comment]
A PR mentioning planned release or released versions will be welcomed 🌹

**Comment by mikle111** [comment]
Ok. But then some your articles from book are not actual, so it cant be fully used as reference. Somebody(like me today) can read about some feature of Type Script and will not be able to use it. Iv spent some time to figure out, why feature doesent work. Its not obvious. Maybe its good idea to add some mark or warning for features that are not implemented yet?

**Comment by basarat** [comment]
> Maybe its good idea to add some mark or warning for features that are not implemented yet?

Good idea :+1: 

FWIW https://basarat.gitbooks.io/typescript/content/docs/getting-started.html mentions nightly typescript. After all, their tests are better than our code bases. :rose:

**Comment by mikle111** [comment]
If Il get to some article from google, Il not be reading "Getting Started", but that article

**Comment by mikle111** [comment]
Maybe its wrong way of using this book :smile: but seems pretty legal(and common) for me
