### ISSUE TITLE
Destructuring - Assigning to new variable names.

### ISSUE THREAD

**Issue by mdenieffe** [basarat/typescript-book#94]
This is just a suggestion, but maybe an example on how to assign properties to new variable names would be of benefit. My issue was that some of the properties contained spaces so I didn't know how to assign them.

E.G
```
var obj = {"some property": "some value", anotherProperty: "another value"};

//destructure
var {"some property": someProperty, anotherProperty} = obj;
//someProperty="some value"; 
```

Thanks for an excellent resource.

**Comment by basarat** [comment]
Thanks! Feel free to PR the following :rose: 
```ts
// structure
const obj = {"some property": "some value"};

// destructure
const {"some property": someProperty} = obj;

console.log(someProperty === "some value"); // true 
```

**Comment by mdenieffe** [comment]
added the suggestion above to #95

**Comment by basarat** [comment]
Merged :rose:
