### ISSUE TITLE
Class child vs class children

### ISSUE THREAD

**Issue by thefabulousdev** [basarat/typescript-book#98]
I have been kinda confused while reading `classes.md`, the term `class child` is used everywhere, but to my understanding the correct term to use would be `class children`, I can change this but I am not completely sure to be right. 

Can perhaps some native english speaker developer assist on this one?

**Comment by basarat** [comment]
> the term class child is used everywhere,

I am not seeing this. Only see `class children`: 

![image](https://cloud.githubusercontent.com/assets/874898/14623601/0ce9dd4a-0617-11e6-8411-ea9918765547.png)

Maybe you have an older copy of the book? :rose:

**Comment by thefabulousdev** [comment]
That I changed on a previous PR, but all around the page (just search for the "class child") it's used. If its agreed it should be class children I'll start changing it whenever I see it.

**Comment by basarat** [comment]
Please do. Thanks a tonne 🌹

**Comment by basarat** [comment]
closing for now :heart:
