### ISSUE TITLE
Fat arrows wrong encouraged usage

### ISSUE THREAD

**Issue by thefabulousdev** [basarat/typescript-book#99]
[Here](https://github.com/basarat/typescript-book/blob/master/docs/arrow-functions.md#arrow-functions) is said 

> Note that since you are using TypeScript you can be even sweeter in syntax and combine arrows with classes

Followed by 

```ts
class Person {
    constructor(public age:number) {}
    growOld = () => {
        this.age++;
    }
}
var person = new Person(1);
setTimeout(person.growOld,1000);

setTimeout(function() { console.log(person.age); },2000); // 2
```

I see no reason to employ fat arrow on class members as they are already bind to the correct context and generate an extra unnecessary function context wrap.

The previous could be substituted with 

```ts 

class Person {
    constructor(public age:number) {}
    growOld(){
        this.age++;
    }
}
var person = new Person(1);
setTimeout(person.growOld,1000);

setTimeout(function() { console.log(person.age); },2000); // 2
```

See demo [here](https://www.typescriptlang.org/play/#src=class%20Person%20%7B%0D%0A%20%20%20%20constructor(public%20age%3Anumber)%20%7B%7D%0D%0A%20%20%20%20growOld%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20this.age%2B%2B%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Avar%20person%20%3D%20new%20Person(1)%3B%0D%0AsetTimeout(person.growOld%2C1000)%3B%0D%0A%0D%0AsetTimeout(function()%20%7B%20console.log(person.age)%3B%20%7D%2C2000)%3B%20%2F%2F%202%0D%0A%0D%0A%0D%0Aclass%20NicePerson%20%7B%0D%0A%20%20%20%20constructor(public%20age%3Anumber)%20%7B%7D%0D%0A%20%20%20%20growOld()%7B%0D%0A%20%20%20%20%20%20%20%20this.age%2B%2B%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Avar%20nicePerson%20%3D%20new%20NicePerson(1)%3B%0D%0AsetTimeout(nicePerson.growOld%2C1000)%3B%0D%0A%0D%0AsetTimeout(function()%20%7B%20console.log(nicePerson.age)%3B%20%7D%2C2000)%3B%20%2F%2F%202)

**Comment by thefabulousdev** [comment]
I see that after the stated, this is mentioned as a TIP:

> Beyond the terse syntax, you only need to use the fat arrow if you are going to give the function to someone else to call.

 I believe we should come up with a better usecase which reflects the need to use fat arrow functions in classes and not just because we can.

**Comment by basarat** [comment]
> The previous could be substituted with

Nope. I see `1` in the second example from your demo: 

![image](https://cloud.githubusercontent.com/assets/874898/14623557/a9d04e74-0616-11e6-8c3f-c8e59cf1aabd.png)

> class members as they are already bind to the correct context 

Not true actually :rose:

**Comment by thefabulousdev** [comment]
I stand corrected :)
